title:            Hendrik Heuer
description:      
disqus_shortname: subjecttochanges
#url:              http://hen-drik.de
url:              http://h10r.github.io
#url:              http://0.0.0.0:4000

# Owner/author information
owner:
  name:           Hendrik
  avatar:         bio-photo.jpg
  bio:            "I'm a student in Human-Computer Interaction and Design and Machine Learning at KTH Stockholm and Aalto Helsinki."
  email:          My full name at gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:        hen_drik
  facebook:       
  github:         h10r
  stackexchange:  
  linkedin:       hendrikheuer
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-38376204-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Projects
    url: /projects/
  - title: Articles
    url: /articles/
  - title: Travel Blog
    url: /travel-blog/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Stockholm
future:      true
pygments:    true
markdown:    kramdown
